baseURL                = "https://hungnguyen148.github.io/frstblog/"
languageCode           = "vi"
title                  = "The Villain Hub"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "en"
# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = false

theme = "hugo-theme-stack"

# Ignore goldmark raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

[markup.goldmark.renderer]
    unsafe = true

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
